Fix for CLOUD-3928, Evolve support for custom Galleon feature-packs usage during s2i
wildfly/wildfly-cekit-modules pull request #224
Opened 2021-03-25 15:37 UTC by jfdenise

2021-03-25 20:24 UTC, luck3y commented on jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
> +     for fp in $(echo $GALLEON_PROVISION_FEATURE_PACKS | sed "s/,/ /g"); do
I think it might be a lot safer to write this as -n "${GALLEON_PROVISION_FEATURE_PACKS}" especially if this could have spaces in the provided value.

2021-03-25 20:26 UTC, luck3y commented on jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
> +      log_error "Error, GALLEON_PROVISION_SERVER or GALLEON_PROVISION_LAYERS can't be used at the same time."
Probably better written as '"Error, GALLEON_PROVISION_SERVER **and** GALLEON_PROVISION_LAYERS can't be used at the same time."

2021-03-25 20:27 UTC, luck3y requested changes
Looks fine, other than the couple of mentioned things.

2021-03-26 08:49 UTC, jfdenise commented
@luck3y , thank-you. Fixed.

2021-03-26 13:46 UTC, luck3y approved these changes

2021-04-28 08:03 UTC, merged